@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam ClassAttributeIconSize 0

class Tree{
    -root : TreeNode
    <<Constructor>> Tree()
    <<Constructor>> Tree(TreeNode)

    +setRoot : void
    +getRoot : TreeNode

    +getNode(int) : TreeNode
    +add(int) : void
    +preOrderTraversal() : void
    +inOrderTraversal() : void
    +postOrderTraversal() : void
    +preOrderHelper(TreeNode) : void
    +inOrderHelper(TreeNode) : void
    +postOrderHelper(TreeNode) : void
    +getParent(int) : TreeNode
    +getPredessor(TreeNode) : TreeNode
    +remove(int) : boolean


}

class TreeNode{
    -data      : int
    -leftNode  : TreeNode
    -rightNode : TreeNode
    <<Constructor>> TreeNode(int)

    +setData(int) : void
    +getData() : int
    +setLeftNode(TreeNode) : void
    +getLeftNode() : TreeNode
    +setRightNode(TreeNode) : void
    +getRightNode() : TreeNode
    +isLeaf() : boolean
}

Tree "1" *===> "1" TreeNode

@enduml